// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BeBfGVhQpyvMlRfuMwX1OZzob8bkkB4',
    appId: '1:224806645411:web:f7c89ad7cb648f8a2f9916',
    messagingSenderId: '224806645411',
    projectId: 'notetaker-a32e4',
    authDomain: 'notetaker-a32e4.firebaseapp.com',
    storageBucket: 'notetaker-a32e4.firebasestorage.app',
    measurementId: 'G-Y7KLW96JFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMltcBtGEc9mgP556YrIZVcaMfrXR3qsc',
    appId: '1:224806645411:android:6b691d0d289f70712f9916',
    messagingSenderId: '224806645411',
    projectId: 'notetaker-a32e4',
    storageBucket: 'notetaker-a32e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQX1VWv5vCdPktKz_CABd48w9i8GCY29A',
    appId: '1:224806645411:ios:f679eaf7039d9ca12f9916',
    messagingSenderId: '224806645411',
    projectId: 'notetaker-a32e4',
    storageBucket: 'notetaker-a32e4.firebasestorage.app',
    iosBundleId: 'com.example.notetaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQX1VWv5vCdPktKz_CABd48w9i8GCY29A',
    appId: '1:224806645411:ios:f679eaf7039d9ca12f9916',
    messagingSenderId: '224806645411',
    projectId: 'notetaker-a32e4',
    storageBucket: 'notetaker-a32e4.firebasestorage.app',
    iosBundleId: 'com.example.notetaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5BeBfGVhQpyvMlRfuMwX1OZzob8bkkB4',
    appId: '1:224806645411:web:80d034718106934c2f9916',
    messagingSenderId: '224806645411',
    projectId: 'notetaker-a32e4',
    authDomain: 'notetaker-a32e4.firebaseapp.com',
    storageBucket: 'notetaker-a32e4.firebasestorage.app',
    measurementId: 'G-GHCCXTXYBC',
  );
}
